//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMindHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BR213IC-GC-EL_MY16</string>
  <string>BR213IC-GC-EL_MY17</string>
  <string>BR213IC-GC-EL_MY18</string>
  <string>BR213IC-GC-EL_SOP</string>
  <string>BR213IC-GC-EL205MY18</string>
  <string>BR213IC-GC-HL_MY16</string>
  <string>BR213IC-GC-HL_MY17</string>
  <string>BR213IC-GC-HL_MY18</string>
  <string>BR213IC-GC-HL_SOP</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Projects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Projects"]));
            }
            set {
                this["Projects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>E24</string>
  <string>E25</string>
  <string>E27</string>
  <string>E32</string>
  <string>E33</string>
  <string>E34</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SamplePhase {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SamplePhase"]));
            }
            set {
                this["SamplePhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>pre10</string>\r\n  <string>pre15</string>\r\n  <string>pre20</string>\r\n  <str" +
            "ing>pre21</string>\r\n  <string>pre22</string>\r\n  <string>pre23</string>\r\n  <strin" +
            "g>pre24</string>\r\n  <string>pre25</string>\r\n  <string>pre26</string>\r\n  <string>" +
            "pre27</string>\r\n  <string>pre28</string>\r\n  <string>pre29</string>\r\n  <string>pr" +
            "e30</string>\r\n  <string>pre31</string>\r\n  <string>pre32</string>\r\n  <string>pre3" +
            "3</string>\r\n  <string>pre34</string>\r\n  <string>pre35</string>\r\n  <string>pre36<" +
            "/string>\r\n  <string>pre37</string>\r\n  <string>pre38</string>\r\n  <string>pre39</s" +
            "tring>\r\n  <string>pre40</string>\r\n  <string>pre41</string>\r\n  <string>pre42</str" +
            "ing>\r\n  <string>pre43</string>\r\n  <string>pre44</string>\r\n  <string>pre45</strin" +
            "g>\r\n  <string>pre46</string>\r\n  <string>pre47</string>\r\n  <string>pre48</string>" +
            "\r\n  <string>pre49</string>\r\n  <string>pre50</string>\r\n  <string>pre51</string>\r\n" +
            "  <string>pre52</string>\r\n  <string>pre53</string>\r\n  <string>pre54</string>\r\n  " +
            "<string>pre55</string>\r\n  <string>pre56</string>\r\n  <string>pre57</string>\r\n  <s" +
            "tring>pre58</string>\r\n  <string>pre59</string>\r\n  <string>pre60</string>\r\n  <str" +
            "ing>pre61</string>\r\n  <string>pre62</string>\r\n  <string>pre63</string>\r\n  <strin" +
            "g>pre64</string>\r\n  <string>pre65</string>\r\n  <string>pre66</string>\r\n  <string>" +
            "pre67</string>\r\n  <string>pre68</string>\r\n  <string>pre69</string>\r\n  <string>pr" +
            "e70</string>\r\n  <string>pre71</string>\r\n  <string>pre72</string>\r\n  <string>pre7" +
            "3</string>\r\n  <string>pre74</string>\r\n  <string>pre75</string>\r\n  <string>pre76<" +
            "/string>\r\n  <string>pre77</string>\r\n  <string>pre78</string>\r\n  <string>pre79</s" +
            "tring>\r\n  <string>pre80</string>\r\n  <string>pre81</string>\r\n  <string>pre82</str" +
            "ing>\r\n  <string>pre83</string>\r\n  <string>pre84</string>\r\n  <string>pre85</strin" +
            "g>\r\n  <string>pre86</string>\r\n  <string>pre87</string>\r\n  <string>pre88</string>" +
            "\r\n  <string>pre89</string>\r\n  <string>pre90</string>\r\n  <string>pre91</string>\r\n" +
            "  <string>pre92</string>\r\n  <string>pre93</string>\r\n  <string>pre94</string>\r\n  " +
            "<string>pre95</string>\r\n  <string>pre96</string>\r\n  <string>pre97</string>\r\n  <s" +
            "tring>pre98</string>\r\n  <string>pre99</string>\r\n  <string>pre100</string>\r\n</Arr" +
            "ayOfString>")]
        public global::System.Collections.Specialized.StringCollection SWRelease {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SWRelease"]));
            }
            set {
                this["SWRelease"] = value;
            }
        }
    }
}
